spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:originalapp
    username: sa
    password: 
  mvc:
    hiddenmethod:
      filter:
        enabled: true

  h2:
    console:
      enabled: true
      

 
cloud:
  aws:
    stack:
      auto: false
    region:
      auto: false
      static: ap-northeast-1